In [ ]:
# to study numpy 

In [1]:
import numpy as np

In [2]:
np.array([5, 9, 13])

array([ 5,  9, 13])

In [3]:
type([5, 9, 13])

list

In [6]:
a = np.array([[5,9], [10, 11], [20,21]])
print("Type",a.dtype)
print("\n","*"*30)
print("\n", a)

Type int32

 ******************************

 [[ 5  9]
 [10 11]
 [20 21]]


In [9]:
# conversion of dtype(data type)
np.array([1, 2, 3], dtype=float)


array([1., 2., 3.])

In [13]:
#cerating array using .mat(matrix)
np.array(np.mat('1 2 3; 3  4  5'))

array([[1, 2, 3],
       [3, 4, 5]])

In [14]:
# convert list in to array
a= [1,2,3,4,5,6]
b=np.array(a)
print(b)

[1 2 3 4 5 6]


In [15]:
# copy array in to other
c=np.array(b)
print(c)

[1 2 3 4 5 6]
